### ISSUE TITLE
What happend if the conversations listed at random places?

### ISSUE THREAD

**Issue by MeSagor** [akifislam/Automate-Deleting-Old-Facebook-Conversations#1]
Suppose i have 5 conversations,
I want to delete **1st**, **4th** & **5th** conversations.

**Comment by akifislam** [comment]
Yes, this is a very good question. There are number of ways we can solve this problem.

## Solution 1 - Moving the Mouse Cursor manually

- As I have designed the program with PyAutoGUI, here, after 1 deletion is executed, we can set 10 second delay to change the  position of mouse cursor manually by the user. 
- Actually, The program deletes the conversation that it gets under the cursor.
- So, as per your requirement, after deleting the 1st conversation, when it will try to delete 2nd conversion, we will move the mouse cursor to the 4th one (within the 10 second delay). And it will work perfectly. 

N.B : I have also used this technique while deleting 1000 conversations

## Solution 2 - Set Auto Scrolling with PyAutoGUI

- Another solution will be excellent in such cases where we want to delete every odd conversations. 
- Suppose, 1st, 3rd, 5th, 7th ... 10001th.
- Here we can call pyautogui.mouseScroll() whichi will scroll by its own to get the odd messages. 

## Solution 3 - Using Selenium or Scrapy

- With Selenium, we can detect and delete message by its HTML element. But the disadvantage of this module is the requirement of Facebook authentication. Facebook doesn't want anyone to use BOT on their web-services. They may disable our account for this kind of actions.
- The best possible solution we can design is with Scrapy. Scrapy is an advanced scraping (some people call it 'spider') tool where we can take decisions by checking other attributes.
- Suppose we want to delete every conversations where the person's gender is 'Female'
- Or, suppose we want to delete every conversations where person lives in certain area.

## Then why I use PyAutoGUI over other techniques ?
Because:
- It took only 5 minutes to write the whole script that works buttery smooth.
- I don't have any confusion or fear of losing my Facebook ID because it is just an automated mouse moving technique. No Authentication is required.
- My problem statement was easy enough. I wanted to keep last 50 conversations and wanted to delete other 1000+ conversations. So, I started the script at 51th conversation and it ended successfully after deleting everything.

Thanks for asking the question. I hope you have got the answer.
